# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "staging" ]

jobs:
  build:

    runs-on: [self-hosted, Linux, X64, staging]

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - run: npm ci

    - name: 'Build project'
      run: npm run build:linux

    - name: 'Deploy to staging'
      run: |
        echo "${{ secrets.HOME_X502CA_SUDO_PASSWORD }}" | sudo -S systemctl stop marketing4than.service
        echo "${{ secrets.HOME_X502CA_SUDO_PASSWORD }}" | sudo -S rm -rf ~/Desktop/Marketing4than-linux-x64
  
    - name: 'Copy files to Desktop'
      run: cp -r out/Marketing4than-linux-x64 ~/Desktop
    
    - name: 'Change permissions'
      run: chmod +x ~/Desktop/Marketing4than-linux-x64/Marketing4than

    - name: 'Restart and enable service'
      run: |
        echo "${{ secrets.HOME_X502CA_SUDO_PASSWORD }}" | sudo -S bash -c '
        systemctl restart marketing4than.service
        systemctl enable marketing4than.service
        '
